server:
  error:
    whitelabel:
      enabled: false


kakao:
  restKey:
  adminKey:

st11:
  apiKey:

google:
  apiKey:

spring:
  servlet:
    multipart:
      # location: ${java.io.tmpdir}
  http:
    converters:
      preferred-json-mapper: gson
